import Head from "next/head";
import { Container } from "@interchain-ui/react";
import { Header } from "./Header";
import { Footer } from "./Footer";
import BgImage from "@/public/qVotvbsuM_c.jpg";

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <Container
      maxWidth="64rem"
      attributes={{
        py: "$14",
        minHeight: "100vh",
      }}
    >
      <Head>
        <title>CosmonautJukeBox</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </Container>
  );
}
